### ISSUE TITLE
RN 0.59.0 ,react-native-fix-image not works

### ISSUE THREAD

**Issue by PhoenixLeeSin** [huylvdev/react-native-fix-image#4]
in RN 0.59.0, react-native-fix-image not works. it can not find RCTUIImageViewAnimated.m; any solutions??

**Comment by imhuy** [comment]
@PhoenixLeeSin  pod update SDWebImage or you can remove Podfile.lock and run pod install --repo-update

**Comment by PhoenixLeeSin** [comment]
@huylvdev  it work well now with do nothing.... thanks a lot
